name: Feature Request
description: Request a new feature
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        Hi 👋, thanks for taking the time to request a new feature!

        Please try to give your feature request a good title. Try using a brief description of what you'd like to see.
        Like this:
        - `Add the ability to easily swap an OnCall shift with one of my teammates` or
        - `Within Slack, push a button and magically fix my alert`
  - type: textarea
    id: feature-describe
    attributes:
      label: What would you like to see?
      description: Describe what painpoint(s) this new feature would solve. How would you envision it working?
    validations:
      required: true
